#!/bin/bash
# Script to run on VPS to fix template files

echo "🔧 Fixing Template Files on VPS..."
echo ""

echo "Run these commands on the VPS:"
echo ""
echo "1. Navigate to project directory:"
echo "   cd /opt/flipunit"
echo ""
echo "2. Check current git status:"
echo "   git status"
echo "   git log --oneline -5"
echo ""
echo "3. Force pull latest changes:"
echo "   git fetch origin"
echo "   git reset --hard origin/main"
echo ""
echo "4. Verify template files are updated:"
echo "   grep 'placeholder=' templates/pdf_tools/html_to_pdf.html | grep html_content"
echo "   grep 'placeholder=' templates/pdf_tools/universal.html | grep html_content"
echo "   # Should show: placeholder=\"Paste your HTML content here\""
echo ""
echo "5. Since templates are volume-mounted, just restart container:"
echo "   docker-compose restart web"
echo ""
echo "6. Wait a few seconds, then verify:"
echo "   sleep 5"
echo "   curl -s https://flipunit.eu/pdf-tools/html-to-pdf/ | grep -o 'textarea[^>]*placeholder=\"[^\"]*\"' | grep html_content"
echo "   # Should show: placeholder=\"Paste your HTML content here\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  If files still show old content after git reset:"
echo "   1. Check if files are actually updated: cat templates/pdf_tools/html_to_pdf.html | grep placeholder"
echo "   2. Check for template caching (Django may cache templates)"
echo "   3. Try: docker-compose restart web (may need full restart)"
