#!/bin/bash
# Force deploy the duplicate tag fix to VPS

echo "🔧 Force Deploying Duplicate Tag Fix..."
echo ""

echo "1. Checking current state on VPS..."
echo "   Run these commands on VPS:"
echo ""
echo "   cd /opt/flipunit"
echo "   git fetch origin"
echo "   git log --oneline -5"
echo "   git status"
echo ""
echo "2. Force pull latest changes:"
echo "   git reset --hard origin/main"
echo "   git pull origin main"
echo ""
echo "3. Verify files are updated:"
echo "   grep -A 1 'textarea.*html_content' templates/pdf_tools/html_to_pdf.html"
echo "   grep -A 1 'textarea.*html_content' templates/pdf_tools/universal.html"
echo ""
echo "4. Rebuild and restart container:"
echo "   docker-compose down"
echo "   docker-compose up -d --build web"
echo ""
echo "5. Verify fix is live:"
echo "   curl -s https://flipunit.eu/pdf-tools/html-to-pdf/ | grep -o 'textarea[^>]*placeholder=\"[^\"]*\"' | grep html_content"
echo "   # Should show: placeholder=\"Paste your HTML content here\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  If files are mounted as volumes, you may need to:"
echo "   1. Check docker-compose.yml for volume mounts"
echo "   2. Copy files directly into container if volumes override"
echo "   3. Or rebuild container without volume mounts for templates"
