# Generated by Django 5.2.9 on 2026-01-09 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('operation', models.CharField(choices=[('image_converter', 'Image Converter'), ('image_resize', 'Image Resize'), ('image_merge', 'Image Merge'), ('svg_to_png', 'SVG to PNG'), ('batch_converter', 'Batch Converter')], max_length=30)),
                ('file_key', models.CharField(max_length=500)),
                ('output_file_key', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('output_format', models.CharField(blank=True, max_length=20, null=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='image_conve_status_dc3143_idx'), models.Index(fields=['user_ip', 'created_at'], name='image_conve_user_ip_3f2606_idx')],
            },
        ),
    ]
