"""
Django settings for flipunit project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be set via environment variable
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Only allow default key in development
        SECRET_KEY = 'django-insecure-&c@o820#bmef_172)$k3t-u5wbi65+k7!u6x1n*%k5evy95qqs'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production!")

# Parse ALLOWED_HOSTS from environment, stripping whitespace from each hostname
if os.environ.get('ALLOWED_HOSTS'):
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS').split(',')]
else:
    # Default hosts. On the server, .env can override. Hetzner VPS IP included for direct IP access.
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '192.168.1.135', 'flipunit.eu', 'www.flipunit.eu']
    else:
        ALLOWED_HOSTS = ['flipunit.eu', 'www.flipunit.eu', '46.225.75.195']

# CSRF Trusted Origins - required for HTTPS requests
CSRF_TRUSTED_ORIGINS = []
if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS').split(',')]
else:
    # Default trusted origins
    CSRF_TRUSTED_ORIGINS = [
        'https://flipunit.eu',
        'https://www.flipunit.eu',
        'http://flipunit.eu',  # For development/testing
        'http://www.flipunit.eu',  # For development/testing
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'flipunit',  # Main project app (needed for management commands)
    'converters',
    'image_converter',
    'media_converter',
    'pdf_tools',
    'currency_converter',
    'utilities',
    'color_picker',
    'archive_converter',
    'text_converter',
    'developer_converter',
    'isdown',
    'youtube_thumbnail',
    'ai_chat',
]

# Django Sites Framework
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flipunit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'flipunit.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'flipunit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Set USE_SQLITE=1 in .env to use SQLite for local dev (no PostgreSQL role needed).

if os.environ.get('USE_SQLITE', '').strip() == '1':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'flipunit'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 300,  # Connection pooling: reuse connections for 5 minutes
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Long cache for hashed static assets (1 year); WhiteNoise applies where appropriate
WHITENOISE_MAX_AGE = 31536000

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SEO Settings
SITE_NAME = 'FlipUnit'
SITE_DISPLAY_NAME = 'flipunit'  # Display name for navbar (without .eu)
SITE_DESCRIPTION = 'Simple, fast, no-login online converter hub - unit converters, image converters, media converters, and everyday utilities.'
SITE_URL = os.environ.get('SITE_URL', 'https://flipunit.eu')

# Google Gemini API Key
GOOGLE_GEMINI_API_KEY = os.environ.get('GOOGLE_GEMINI_API_KEY')

# OpenAI API Key (for Whisper audio transcription)
# Must be set in .env file: OPENAI_API_KEY=your_key_here
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')

# Redis Configuration
REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = 900  # 15 minutes default soft timeout
CELERY_TASK_TIME_LIMIT = 960  # 16 minutes default hard timeout

# Celery Task Routes - Queue routing for different operation types
CELERY_TASK_ROUTES = {
    'text_converter.tasks.transcribe_audio_task': {'queue': 'transcription'},
    'text_converter.tasks.generate_docx_task': {'queue': 'lightweight'},
    'media_converter.tasks.*': {'queue': 'media_processing'},
    'pdf_tools.tasks.*': {'queue': 'pdf_processing'},
    'image_converter.tasks.*': {'queue': 'image_processing'},
    'archive_converter.tasks.*': {'queue': 'archive_processing'},
    'currency_converter.tasks.*': {'queue': 'api_calls'},
    'ai_chat.tasks.*': {'queue': 'api_calls'},
}

# Celery Task Queues Configuration
CELERY_TASK_QUEUES = {
    'transcription': {
        'exchange': 'transcription',
        'routing_key': 'transcription',
    },
    'media_processing': {
        'exchange': 'media_processing',
        'routing_key': 'media_processing',
    },
    'pdf_processing': {
        'exchange': 'pdf_processing',
        'routing_key': 'pdf_processing',
    },
    'image_processing': {
        'exchange': 'image_processing',
        'routing_key': 'image_processing',
    },
    'archive_processing': {
        'exchange': 'archive_processing',
        'routing_key': 'archive_processing',
    },
    'lightweight': {
        'exchange': 'lightweight',
        'routing_key': 'lightweight',
    },
    'api_calls': {
        'exchange': 'api_calls',
        'routing_key': 'api_calls',
    },
}

# Cache Configuration (Redis)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://redis:6379/2'),  # Use DB 2 for cache
        'KEY_PREFIX': 'flipunit_cache',
        'TIMEOUT': 300,  # Default timeout 5 minutes
    }
}

# Session Configuration (Redis)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 24 hours

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 734003200  # 700MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 734003200  # 700MB

# Request timeout settings (for long-running operations like media conversion)
# Note: For production, consider using async tasks (Celery) for long operations
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Security settings for production
if not DEBUG:
    # IMPORTANT: SSL settings configuration
    # If you're behind Nginx/Reverse Proxy with HTTPS:
    # 1. Ensure Nginx sends X-Forwarded-Proto header
    # 2. Uncomment SECURE_PROXY_SSL_HEADER below
    # 3. Set SECURE_SSL_REDIRECT = True
    # 4. Set SESSION_COOKIE_SECURE = True
    # 5. Set CSRF_COOKIE_SECURE = True
    
    # SSL redirect is handled by Nginx, so we don't need Django to redirect
    # This prevents redirect loops since Nginx already redirects HTTP to HTTPS
    SECURE_SSL_REDIRECT = False  # Nginx handles HTTP to HTTPS redirect
    
    # Enable secure cookies since we're using HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Basic security headers (always enabled)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS (HTTP Strict Transport Security) - Enabled for security
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Trust proxy headers from Nginx (REQUIRED if using Nginx reverse proxy)
    # Nginx is configured to send X-Forwarded-Proto header
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'flipunit.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'json' if not DEBUG else 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'] if not DEBUG else ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'media_converter': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_chat': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'text_converter': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
logs_dir = os.path.join(BASE_DIR, 'logs')
os.makedirs(logs_dir, exist_ok=True)

# Sentry integration (optional)
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.celery import CeleryIntegration
        
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                CeleryIntegration(),
            ],
            traces_sample_rate=0.1,  # 10% of transactions
            send_default_pii=False,  # Don't send PII
            environment='production' if not DEBUG else 'development',
        )
    except ImportError:
        pass  # Sentry SDK not installed
