"""
Django settings for flipunit project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be set via environment variable
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Only allow default key in development
        SECRET_KEY = 'django-insecure-&c@o820#bmef_172)$k3t-u5wbi65+k7!u6x1n*%k5evy95qqs'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production!")

# Parse ALLOWED_HOSTS from environment, stripping whitespace from each hostname
if os.environ.get('ALLOWED_HOSTS'):
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS').split(',')]
else:
    # Default hosts: domain names and server IP address
    # Include localhost and 127.0.0.1 for local development
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '192.168.1.135', 'flipunit.eu', 'www.flipunit.eu', '217.146.78.140']
    else:
        ALLOWED_HOSTS = ['flipunit.eu', 'www.flipunit.eu', '217.146.78.140']

# CSRF Trusted Origins - required for HTTPS requests
CSRF_TRUSTED_ORIGINS = []
if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS').split(',')]
else:
    # Default trusted origins
    CSRF_TRUSTED_ORIGINS = [
        'https://flipunit.eu',
        'https://www.flipunit.eu',
        'http://flipunit.eu',  # For development/testing
        'http://www.flipunit.eu',  # For development/testing
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'flipunit',  # Main project app (needed for management commands)
    'converters',
    'image_converter',
    'media_converter',
    'pdf_tools',
    'currency_converter',
    'utilities',
    'color_picker',
    'archive_converter',
    'text_converter',
    'developer_converter',
    'isdown',
    'youtube_thumbnail',
    'ai_chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flipunit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'flipunit.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'flipunit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'flipunit'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SEO Settings
SITE_NAME = 'FlipUnit'
SITE_DISPLAY_NAME = 'flipunit'  # Display name for navbar (without .eu)
SITE_DESCRIPTION = 'Simple, fast, no-login online converter hub - unit converters, image converters, media converters, and everyday utilities.'
SITE_URL = os.environ.get('SITE_URL', 'https://flipunit.eu')

# Google Gemini API Key
GOOGLE_GEMINI_API_KEY = os.environ.get('GOOGLE_GEMINI_API_KEY')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 734003200  # 700MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 734003200  # 700MB

# Request timeout settings (for long-running operations like media conversion)
# Note: For production, consider using async tasks (Celery) for long operations
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Security settings for production
if not DEBUG:
    # IMPORTANT: SSL settings configuration
    # If you're behind Nginx/Reverse Proxy with HTTPS:
    # 1. Ensure Nginx sends X-Forwarded-Proto header
    # 2. Uncomment SECURE_PROXY_SSL_HEADER below
    # 3. Set SECURE_SSL_REDIRECT = True
    # 4. Set SESSION_COOKIE_SECURE = True
    # 5. Set CSRF_COOKIE_SECURE = True
    
    # Currently disabled to avoid redirect loops - RE-ENABLE AFTER NGINX SSL CONFIGURATION
    SECURE_SSL_REDIRECT = False  # Set to True after Nginx SSL is configured
    SESSION_COOKIE_SECURE = False  # Set to True after Nginx SSL is configured
    CSRF_COOKIE_SECURE = False  # Set to True after Nginx SSL is configured
    
    # Basic security headers (always enabled)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS (HTTP Strict Transport Security) - Enable after SSL is working
    # SECURE_HSTS_SECONDS = 31536000  # 1 year
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
    
    # Trust proxy headers from Nginx (REQUIRED if using Nginx reverse proxy)
    # Uncomment this line AFTER confirming Nginx sends X-Forwarded-Proto header
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'media_converter': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
