# Generated by Django 5.2.9 on 2026-01-09 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_key', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('transcription_text', models.TextField(blank=True, null=True)),
                ('detected_language', models.CharField(blank=True, max_length=10, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='text_conver_status_018e6b_idx'), models.Index(fields=['user_ip', 'created_at'], name='text_conver_user_ip_2d6f81_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('daily_count', models.IntegerField(default=0)),
                ('monthly_count', models.IntegerField(default=0)),
                ('last_reset_daily', models.DateField(auto_now=True)),
                ('last_reset_monthly', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_reset_daily'],
                'indexes': [models.Index(fields=['ip_address'], name='text_conver_ip_addr_44ea1b_idx')],
            },
        ),
    ]
