# Generated by Django 5.2.11 on 2026-02-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediajob',
            name='operation',
            field=models.CharField(choices=[('video_converter', 'Video Converter'), ('video_merge', 'Video Merge'), ('audio_converter', 'Audio Converter'), ('audio_merge', 'Audio Merge'), ('video_to_gif', 'Video to GIF'), ('video_compressor', 'Video Compressor'), ('mp4_to_mp3', 'MP4 to MP3'), ('mute_video', 'Mute Video'), ('reduce_noise', 'Reduce Noise'), ('audio_splitter', 'Audio Splitter')], max_length=30),
        ),
    ]
